# Import the secret file if it exists
spring.config.import=optional:classpath:application-secret.properties

# -------------------------------------
# SUPABASE DATABASE (POSTGRES)
# -------------------------------------

# 1. The Host is now the POOLER host
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres

# 2. The Username is the special POOLER username
spring.datasource.username=postgres.kitxtqufhhgosxtskxhy

# 3. The Password comes from an Environment Variable
# spring.datasource.password=${DB_PASSWORD} 

spring.datasource.driver-class-name=org.postgresql.Driver


# -------------------------------------
# JPA / HIBERNATE SETTINGS
# -------------------------------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# -------------------------------------
# SUPABASE JWT SECURITY
# -------------------------------------
# --- This does NOT change ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://kitxtqufhhgosxtskxhy.supabase.co/auth/v1

# -------------------------------------
# SUPABASE JWT SECRET
# -------------------------------------
# This Secret comes from an Environment Variable
# supabase.jwt.secret=${SUPABASE_JWT_SECRET}